# Generated by Django 2.2.6 on 2019-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.CharField(max_length=100),
        ),
    ]
