# Generated by Django 2.2.6 on 2019-10-09 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191005_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
