# Generated by Django 2.2.6 on 2019-10-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_postedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
